# Сборка единого standalone-файла: cat src/*.jl в правильном порядке + запуск.
# Запуск: julia -t auto dist/nsb_lab_standalone.jl --quick
cd "$(dirname "$0")"
ORDER="00_boot.jl 01_i18n.jl 02_ui.jl 04_fontdata.jl 05_colormapdata.jl 03_deflate_png.jl 04_font.jl 05_plots.jl 06_fft.jl 07_solver3d.jl 08_diagnostics.jl 09_ic_bcorr.jl 10_blowup.jl 11_experiments.jl 12_flows.jl 13_roadmap.jl 14_reports.jl 15_pdf.jl 16_final_report.jl 17_cli.jl 18_menu.jl 99_main.jl"
mkdir -p dist
{
  echo "# NSB Julia Lab v1.0.0 — standalone bundle (generated by build_standalone.sh)"
  echo "# Запуск / run: julia -t auto nsb_lab_standalone.jl [--quick|--suite hard|--flow all|...]"
  for f in $ORDER; do
    echo "# ==== src/$f ===="
    cat "src/$f"
  done
  echo "exit(nsb_main(ARGS))"
} > dist/nsb_lab_standalone.jl
echo "OK: dist/nsb_lab_standalone.jl ($(wc -l < dist/nsb_lab_standalone.jl) lines)"
